--1. 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서명, 직급, 입사일, 순위 조회
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE
FROM EMPLOYEE E, DEPARTMENT D, JOB J
ORDER BY ((SALARY + SALARY*(NVL(BONUS,0)))*12) DESC
WHERE E.DEPT_ID = D.DEPT_ID
AND E.JOB_CODE = J.JOB_CODE
AND ((SALARY + SALARY*BONUS) * 12)

SELECT EMP_ID, DEPT_TITLE, JOB_NAME, HIRE_DATE, RANK
FROM( EMPLOYEE