 --1. 춘기술대학교의 학과이름과 계열을 표시하세요
 SELECT DEPARTMENT_NAME "학과명", CATEGORY "계열"
 FROM TB_DEPARTMENT;
 
 --2. 학과별 학과 정원을 출력한다.
 SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.'
 FROM TB_DEPARTMENT;
 
 --3. 국어국문학과에 다니는 여학생중 휴학한 여학생 찾기
 SELECT STUDENT_NAME
 FROM  TB_STUDENT
 WHERE DEPARTMENT_NO = '001' AND 
 SUBSTR(STUDENT_SSN, 8 ,1) = 2 AND
 ABSENCE_YN = 'Y';
 
 --4. 도서관 대출 도서 장기 연체자 찾기
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');
 
 --5. 입학정원이 20이상 30이하인 학과 이름과 계열 출력
 SELECT DEPARTMENT_NAME, CATEGORY
 FROM TB_DEPARTMENT
 WHERE CAPACITY>=20 AND CAPACITY<=30;

 --6. 춘기술대학교 총장알아내기 혼자만 소속학과 없다.
 SELECT PROFESSOR_NAME
 FROM TB_PROFESSOR
 WHERE DEPARTMENT_NO IS NULL;
 
 --7. 전산상 착오로 학과가 지정되어 있지 않은 학생있는지.
 SELECT STUDENT_NAME
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO IS NULL;
 
 --8. 선수과목이 존재하는 과목 여부 확인
 SELECT CLASS_NAME
 FROM TB_CLASS
 WHERE PREATTENDING_CLASS_NO IS NOT NULL;
 
 --9. 춘 대학에는 어떤 계열들이 있는지 확인
 SELECT DISTINCT CATEGORY
 FROM TB_DEPARTMENT;
 
 --10. 휴학한 사람들은 제외한 02학번 전주 거주자들의 학번, 이름, 주민번호
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE,1,2)=02 AND STUDENT_ADDRESS LIKE '전주시%' AND ABSENCE_YN = 'N'; 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 